"""Typed domain models for the Bobi Management API."""

from .automation import (
    Automation,
    AutomationAction,
    AutomationCondition,
    AutomationDraft,
    AutomationList,
    AutomationTarget,
)
from .capability import Capability, CapabilitySetting, CapabilityToggleRequest
from .common import (
    Advanced,
    AutomationType,
    BobiModel,
    ChangePreview,
    DeviceCategory,
    HealthState,
    OperationResult,
    PreviewLine,
    Severity,
    Source,
)
from .device import Device, DeviceList, RawEntity
from .diagnostics import (
    AuditEntry,
    AuditLog,
    DiagnosticIssue,
    DiagnosticsReport,
    TestCase,
    TestReport,
    TestSuite,
)
from .notification import (
    NotificationCondition,
    NotificationList,
    NotificationRule,
    QuietHours,
)
from .probe import (
    ProbeFamily,
    ProbeHistory,
    ProbeHistoryEntry,
    ProbeRequest,
    ProbeResult,
    ProbeSchedule,
    ProbeStep,
    ProbeTarget,
)
from .settings import MASK, SettingField, SettingsResponse, SettingsSection
from .shabbat import (
    SaveTemplateRequest,
    ShabbatConfig,
    ShabbatDeviceSchedule,
    ShabbatDraft,
    ShabbatTemplate,
    ShabbatTimes,
    TimeRange,
)
from .status import (
    ActivityEntry,
    AttentionItem,
    ComponentHealth,
    StatItem,
    SystemStatus,
)
from .task import CalendarEvent, CalendarList, Task, TaskList, TaskUpdateRequest
from .user import (
    PERMISSION_LABELS,
    NotificationPreferences,
    Permission,
    PermissionInfo,
    PermissionUpdateRequest,
    User,
    UserList,
)

__all__ = [
    "MASK",
    "PERMISSION_LABELS",
    "ActivityEntry",
    "Advanced",
    "AttentionItem",
    "AuditEntry",
    "AuditLog",
    "Automation",
    "AutomationAction",
    "AutomationCondition",
    "AutomationDraft",
    "AutomationList",
    "AutomationTarget",
    "AutomationType",
    "BobiModel",
    "CalendarEvent",
    "CalendarList",
    "Capability",
    "CapabilitySetting",
    "CapabilityToggleRequest",
    "ChangePreview",
    "ComponentHealth",
    "Device",
    "DeviceCategory",
    "DeviceList",
    "DiagnosticIssue",
    "DiagnosticsReport",
    "HealthState",
    "NotificationCondition",
    "NotificationList",
    "NotificationPreferences",
    "NotificationRule",
    "OperationResult",
    "Permission",
    "PermissionInfo",
    "PermissionUpdateRequest",
    "PreviewLine",
    "ProbeFamily",
    "ProbeHistory",
    "ProbeHistoryEntry",
    "ProbeRequest",
    "ProbeResult",
    "ProbeSchedule",
    "ProbeStep",
    "ProbeTarget",
    "QuietHours",
    "RawEntity",
    "SaveTemplateRequest",
    "SettingField",
    "SettingsResponse",
    "SettingsSection",
    "Severity",
    "ShabbatConfig",
    "ShabbatDeviceSchedule",
    "ShabbatDraft",
    "ShabbatTemplate",
    "ShabbatTimes",
    "Source",
    "StatItem",
    "SystemStatus",
    "Task",
    "TaskList",
    "TaskUpdateRequest",
    "TestCase",
    "TestReport",
    "TestSuite",
    "TimeRange",
    "User",
    "UserList",
]
